-- 常量定义文件
-- 天策上将·唐太宗（李世民）双形态领袖模组

-- 领袖类型
LEADER_LI_SHIMIN = "LEADER_LI_SHIMIN"
LEADER_TIANCE_GENERAL = "LEADER_TIANCE_GENERAL"
LEADER_EMPEROR_TAIZONG = "LEADER_EMPEROR_TAIZONG"

-- 领袖状态
LEADER_STATE = {
    TIANCE_GENERAL = "TIANCE_GENERAL",
    CORONATION = "CORONATION",
    EMPEROR_TAIZONG = "EMPEROR_TAIZONG",
    PRINCE_LINE = "PRINCE_LINE"
}

-- 单位类型
UNIT_TIANCE_GENERAL = "UNIT_TIANCE_GENERAL"
UNIT_XUANJIA_ARMY = "UNIT_XUANJIA_ARMY"
UNIT_LI_JIANCHENG = "UNIT_LI_JIANCHENG"

-- 建筑类型
BUILDING_XUANWU_GATE = "BUILDING_XUANWU_GATE"

-- 时代
ERA_ANCIENT = "ERA_ANCIENT"
ERA_CLASSICAL = "ERA_CLASSICAL"
ERA_MEDIEVAL = "ERA_MEDIEVAL"

-- 事件名称
EVENTS = {
    ON_GAME_START = "OnGameStart",
    ON_PLAYER_TURN_BEGIN = "OnPlayerTurnBegin",
    ON_PLAYER_TURN_END = "OnPlayerTurnEnd",
    ON_UNIT_CREATED = "OnUnitCreated",
    ON_UNIT_KILLED = "OnUnitKilled",
    ON_CITY_CONQUERED = "OnCityConquered",
    ON_GREAT_PERSON_RECRUITED = "OnGreatPersonRecruited",
    ON_ERA_CHANGED = "OnEraChanged",
    ON_XUANWU_GATE_BUILT = "OnXuanwuGateBuilt",
    ON_SHOOT_LI_JIANCHENG = "OnShootLiJiancheng",
    ON_CORONATION_COMPLETED = "OnCoronationCompleted",
    ON_PRINCE_LINE_ACTIVATED = "OnPrinceLineActivated",
    ON_RESTORATION_COMPLETED = "OnRestorationCompleted",
    ON_RESTORATION_FAILED = "OnRestorationFailed",
    ON_BUILDING_CONSTRUCTED = "OnBuildingConstructed"
}

-- ===== 平衡数值常量 =====

-- 天策上将基础属性
TIANCE_COMBAT = 45
TIANCE_RANGED_COMBAT = 55
TIANCE_RANGE = 2
TIANCE_MOVES = 3
TIANCE_COST = 130

-- 天策军威：周围2格友军战斗力加成
TIANCE_AURA_RANGE = 2
TIANCE_AURA_COMBAT_BONUS = 5

-- 护卫机制：周围2格有友军时无法被选中
GUARD_RANGE = 2

-- 天策府十八学士：每招募1名伟人，首都全产出+6，上限3层（+18）
TALENT_RESERVE_PER_GP = 6
TALENT_RESERVE_MAX_STACKS = 3
TALENT_RESERVE_MAX_BONUS = 18

-- 玄甲军
XUANJIA_COMBAT = 55
XUANJIA_MOVES = 4
XUANJIA_COST = 190

-- 登基线：需攻占5城 + 玄武门建成后3回合
CORONATION_MIN_CITIES_CONQUERED = 5
CORONATION_MIN_TURNS_AFTER_GATE = 3

-- 藩王线：30回合时限 + 需额外征服1城
PRINCE_LINE_TURNS = 30
PRINCE_EXTRA_CONQUESTS_REQUIRED = 1
PRINCE_REMINDER_INTERVAL = 5

-- 藩王线惩罚/增益
PRINCE_SCIENCE_PENALTY = -50
PRINCE_CULTURE_PENALTY = -50
PRINCE_FOOD_PENALTY = -50
PRINCE_MILITARY_PROD_BONUS = 150

-- 贞观之治：每城+3%全产出，上限+24%
ZHENGUAN_PER_CITY_PCT = 3
ZHENGUAN_MAX_PCT = 24

-- 万国来朝：每6回合免费使者
ENVOY_INTERVAL = 6

-- 天可汗智慧：主动宣战-10好感，被宣战+15好感
WAR_DECLARE_PENALTY = -10
DEFENSIVE_WAR_BONUS = 15

-- 剧情通知图标
LISHIMIN_NOTIFY_ICON_XUANWU_GATE = "ICON_LISHIMIN_NOTIFY_XUANWU"
LISHIMIN_NOTIFY_ICON_CORONATION = "ICON_LISHIMIN_NOTIFY_CORONATION"

-- 颜色配置
COLORS = {
    PRIMARY = {R = 0.8, G = 0.2, B = 0.2, A = 1.0},
    SECONDARY = {R = 0.2, G = 0.4, B = 0.8, A = 1.0},
    SUCCESS = {R = 0.2, G = 0.6, B = 0.2, A = 1.0},
    WARNING = {R = 0.8, G = 0.6, B = 0.2, A = 1.0},
    DANGER = {R = 0.8, G = 0.2, B = 0.2, A = 1.0},
    NEUTRAL = {R = 0.5, G = 0.5, B = 0.5, A = 1.0}
}

-- 版本
BALANCE_VERSION = "2.0"
MOD_VERSION = "2.0.0"
MOD_NAME = "天策上将·唐太宗（李世民）"
MOD_AUTHOR = "模组开发者"
MOD_DESCRIPTION = "双形态领袖李世民，体验从马上打天下到下马治天下的完整历程。"

return {
    LEADER_LI_SHIMIN = LEADER_LI_SHIMIN,
    LEADER_TIANCE_GENERAL = LEADER_TIANCE_GENERAL,
    LEADER_EMPEROR_TAIZONG = LEADER_EMPEROR_TAIZONG,
    LEADER_STATE = LEADER_STATE,
    UNIT_TIANCE_GENERAL = UNIT_TIANCE_GENERAL,
    UNIT_XUANJIA_ARMY = UNIT_XUANJIA_ARMY,
    UNIT_LI_JIANCHENG = UNIT_LI_JIANCHENG,
    BUILDING_XUANWU_GATE = BUILDING_XUANWU_GATE,
    EVENTS = EVENTS,
    -- 平衡常量
    CORONATION_MIN_CITIES_CONQUERED = CORONATION_MIN_CITIES_CONQUERED,
    CORONATION_MIN_TURNS_AFTER_GATE = CORONATION_MIN_TURNS_AFTER_GATE,
    PRINCE_LINE_TURNS = PRINCE_LINE_TURNS,
    PRINCE_EXTRA_CONQUESTS_REQUIRED = PRINCE_EXTRA_CONQUESTS_REQUIRED,
    PRINCE_REMINDER_INTERVAL = PRINCE_REMINDER_INTERVAL,
    COLORS = COLORS,
    BALANCE_VERSION = BALANCE_VERSION,
    MOD_VERSION = MOD_VERSION,
    MOD_NAME = MOD_NAME,
    MOD_AUTHOR = MOD_AUTHOR,
    MOD_DESCRIPTION = MOD_DESCRIPTION
}
